version: '3'

vars:
  APP: test1
  PATH: test/test1.go
  # 0 || 1
  CGO_ENABLED: 0
  VERSION: 0.0.1
  BUILDER:
    sh: whoami
  BUILD_DATE:
    sh: date '+%FT%T %A %Z'

tasks:
  default:
    cmds:
      - task: prepare
      - task: build-all
  prepare:
    cmds:
      - go mod tidy
  build-all:
    deps:
      - task: build
        vars: { OS: windows, ARCH: 386, CC: i686-w64-mingw32-gcc, CXX: i686-w64-mingw32-g++, TAGS: jsoniter, UPX: true }
      - task: build
        vars: { OS: windows, ARCH: amd64, CC: x86_64-w64-mingw32-gcc, CXX: x86_64-w64-mingw32-g++, TAGS: jsoniter, UPX: true }
      - task: build
        vars: { OS: darwin, ARCH: arm64, CC: cc, CXX: c++, TAGS: jsoniter, UPX: false }
      - task: build
        vars: { OS: linux, ARCH: amd64, CC: x86_64-linux-musl-gcc, CXX: x86_64-linux-musl-g++, TAGS: sonic avx, UPX: true }
      - task: build
        vars: { OS: linux, ARCH: amd64, CC: x86_64-linux-musl-gcc, CXX: x86_64-linux-musl-g++, TAGS: jsoniter, UPX: true }
      - task: build
        vars: { OS: linux, ARCH: arm64, CC: x86_64-linux-musl-gcc, CXX: x86_64-linux-musl-g++, TAGS: jsoniter, UPX: true }
      - task: build
        vars: { OS: linux, ARCH: mips64, CC: x86_64-linux-musl-gcc, CXX: x86_64-linux-musl-g++, TAGS: jsoniter, UPX: false }
      - task: build
        vars: { OS: linux, ARCH: mips64le, CC: x86_64-linux-musl-gcc, CXX: x86_64-linux-musl-g++, TAGS: jsoniter, UPX: false }
      - task: build
        vars: { OS: linux, ARCH: loong64, CC: x86_64-linux-musl-gcc, CXX: x86_64-linux-musl-g++, TAGS: jsoniter, UPX: false }
  build:
    vars:
      OS: '{{default "UNKNOWN" .OS}}'
      ARCH: '{{default "UNKNOWN" .ARCH}}'
      CC: '{{default "cc" .CC}}'
      CXX: '{{default "c++" .CXX}}'
      EXT: '{{if eq .OS "windows"}}.exe{{end}}'
      TAGS: '{{default "" .TAGS}}'
      UPX: '{{default "" .UPX}}'
      NOAVX: '{{if and (eq .TAGS "sonic avx") (eq .ARCH "amd64")}}-noavx{{end}}'
      NAME: '{{.APP}}-{{.OS}}-{{.ARCH}}{{.NOAVX}}{{.EXT}}'
    cmds:
      - echo {{.NAME}}
      - rm -rf {{.NAME}}  # 文件可以不存在
      - CGO_ENABLED={{.CGO_ENABLED}} CC={{.CC}} CXX={{.CXX}} GOOS={{.OS}} GOARCH={{.ARCH}} go build -ldflags "-X 'main.Version={{.VERSION}}' -X 'main.Builder={{.BUILDER}}' -X 'main.BuildDate={{.BUILD_DATE}}' -s -w" -tags="{{.TAGS}}" -o {{.NAME}} {{.PATH}}
      - if [ {{.UPX}} == "true" ]; then upx -9 {{.NAME}}; fi
