version: '3'

tasks:
  build-windows:
    platforms: [windows]
    cmds:
      - echo 'Running command on Windows'
  a:
    vars:
      A: 0
    cmds:
      - echo {{.A}}
      - A=1
      - echo {{.A}}