version: '3'

tasks:
  build-windows:
    platforms: [windows]
    cmds:
      - echo 'Running command on Windows'
  a:
    vars:
      A: 0
    cmds:
      - echo {{.A}}
      - A=1
      - echo {{.A}}
  default:
    vars:
        x: 111
    cmds:
      - export x=222
      - x=222
      - echo $x
      - x=333
      - echo {{.x}}